### PR TITLE
Allow custom queue options to be set

### PR DESCRIPTION
**Pull request by nward**
Add a new method to CarrotRpc::ClientServer to allow queue options to be set. Options set by the user override defaults (i.e. auto_delete: false in RpcClient).

### CODE REVIEW

**Comment by shamil614** [comment]
Thank you for the contribution! Overall it looks good. I'll need to run it past the other contributors tomorrow.

**Comment by nward** [comment]
I removed the delete_queue method which was not used, and left over from something else I was trying to do. I'm not sure how best to do this - I am testing overriding the default auto_delete option so the queue is not deleted when tests are run, leaving "foo_test" behind. Happy for suggestions here!

Additionally I clarified the 'describe' statements for class methods. Class methods are typically expressed in documentation as Class.method while instance methods are Class#method.

**Comment by shamil614** [comment]
Makes sense that the server queues were hanging around in tests.
My only request is an example in the readme.
Regarding suggestions, we too would like feedback. Obviously this is the best way to provide feedback.

**Comment by shamil614** [comment]
@nward not sure if you saw the previous comment. if we can get an example in the readme, we can get this merged in.

**Comment by nward** [comment]
Sorry, yes I saw it, it's on my to do list - will try get it done tonight (it is 0920 in my TZ right now).

**Comment by nward** [comment]
I've added an example here. I feel that an example only for one of the two (Client/Server) is sufficient as the usage is the same, but can gladly add additional examples if it's deemed necessary.

**Comment by shamil614** [comment]
@nward thank you for the addition to the readme! That one example is good enough for me.

**Comment by shamil614** [comment]
@nward looks like there's a few failures on CI around rubocop. I can get this merged in once CI and CodeClimate are green.

**Comment by nward** [comment]
OK cool let me have a look.

**Comment by nward** [comment]
I have had a look at this, the remaining error on both is the ABC size. I'm not clear on how I should resolve it. The diff that I applied did not change what assignments were made, it was:

```
-    @server_queue = @channel.queue(queue_name)
+    @server_queue = @channel.queue(queue_name, self.class.queue_options)
```

I can't see how this would be resolved without moving some of the instance variables in to instance methods which return defaults, though to do this, `config` would need to be stored.

Some guidance here would be helpful - or, if it isn't too poor form, permission to tell rubocop to ignore ABC size for this method?

**Comment by shamil614** [comment]
@nward To expedite things, I went ahead and made the change to satisfy Rubocrap. https://github.com/C-S-D/carrot_rpc/pull/52

**Comment by nward** [comment]
Haha appropriate name. It seemed like such an arbitrary thing for it to complain about!

**Pull request closed without merging**
